---
project-config-version: 1.1

pivotal:
  project_id: 2531513 # DevOps

service:                  # Values required to deploy the service.
  health: /health         # Override for health check URI.
  port: 8080              # Webserver HTTP port inside Docker container
  replicas:               # How many nodes should be started (per environment).
    dev: 2
    tst: 2
    prd: 3

logging:
  format: json            # Override Splunk Driver log format from default: raw
  sourcetype: _json       # Override Splunk sourcetype from default: log4j_tcs_v2
