---
project-config-version: 

pivotal:
  project_id: # DevOps

service:                  # Values required to deploy the service.
  health:          # Override for health check URI.
  port: 8501              # Webserver HTTP port inside Docker container
  replicas:               # How many nodes should be started (per environment).
    dev: 
    tst: 
    prd: 

logging:
  format:            # Override Splunk Driver log format from default: raw
  sourcetype:       # Override Splunk sourcetype from default: log4j_tcs_v2
