name: build-push-docker

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for the master branch
  push:
    branches:
      - 'master'
    paths:
      - '.project-config.yml'
      - 'requirements.txt'
      - 'Dockerfile'
      - 'config/**'
      - 'src/**'
  # Triggers the workflow on pull requests for the master branch
  pull_request:
    branches:
      - 'master'
    paths:
      - '.project-config.yml'
      - 'requirements.txt'
      - 'Dockerfile'
      - 'config/**'
      - 'src/**'
  # Allows this workflow to be ran manually from the Actions tab
  workflow_dispatch:
    inputs:
      docker-audit:
        type: boolean
        description: Audit Docker Image
      docker-push:
        type: boolean
        description: Push to Docker Hub

jobs:
  call-workflow:
    uses: the-container-store/github-actions-scripts/.github/workflows/build-push-docker.yml@master
    with:
      APP_BUILD_TYPE: python
      APP_NAME: reference-python-app # TODO: Replace me
      APP_TEAM:
      APP_TYPE:
      DOCKER_AUDIT: ${{ github.event.inputs.docker-audit }}
      DOCKER_PUSH: ${{ github.event.inputs.docker-push }}
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      GH_ACTIONS_PAT: ${{ secrets.GH_ACTIONS_PAT }}
      SECURITY_AUDIT_TOKEN: ${{ secrets.SECURITY_AUDIT_TOKEN }}